"""Per-user saved recommendations.

When the user picks one recommendation to build, the rest can be saved
for later. The Save-for-later list persists across sessions so the user
can come back to ideas they liked but didn't build.

Phase 1 single-user-local: backed by a JSON list at
`agent-state/<user_id>/saved_recommendations.json`. Phase 2+ swaps to a
per-user DB table — same interface.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime

from pydantic import BaseModel, ConfigDict, Field

from coordinator.schemas import Recommendation
from core.identity import UserContext
from core.state import state_path

_SAVED_FILE = "saved_recommendations.json"


class SavedRecommendation(BaseModel):
    """One recommendation the user parked for later, with context."""

    model_config = ConfigDict(extra="forbid")

    #: Stable id within the user's saved list. Generated by the store
    #: (`saved_<n>`) on save so two recs with the same R-id from different
    #: plans don't collide.
    id: str = Field(min_length=1)
    role_id: str
    tools: list[str]
    plan_summary: str
    recommendation: Recommendation
    saved_at: datetime


def _path_for(user: UserContext):
    return state_path(user, _SAVED_FILE)


def _read(user: UserContext) -> list[SavedRecommendation]:
    path = _path_for(user)
    if not path.exists():
        return []
    raw = json.loads(path.read_text(encoding="utf-8") or "[]")
    if not isinstance(raw, list):
        return []
    out: list[SavedRecommendation] = []
    for item in raw:
        if not isinstance(item, dict):
            continue
        try:
            out.append(SavedRecommendation.model_validate(item))
        except Exception:
            # Skip malformed entries — better partial than total loss.
            continue
    return out


def _write(user: UserContext, items: list[SavedRecommendation]) -> None:
    path = _path_for(user)
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = [item.model_dump(mode="json") for item in items]
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    tmp.replace(path)


def list_saved(user: UserContext) -> list[SavedRecommendation]:
    """Return all saved recommendations for `user`, newest first."""
    return sorted(_read(user), key=lambda r: r.saved_at, reverse=True)


def save_recommendation(
    user: UserContext,
    *,
    role_id: str,
    tools: list[str],
    plan_summary: str,
    recommendation: Recommendation,
) -> SavedRecommendation:
    """Add a recommendation to the user's saved list. Returns the stored entry."""
    items = _read(user)
    next_n = 1 + max((int(r.id.split("_")[-1]) for r in items if r.id.startswith("saved_")), default=0)
    saved = SavedRecommendation(
        id=f"saved_{next_n:04d}",
        role_id=role_id,
        tools=list(tools),
        plan_summary=plan_summary,
        recommendation=recommendation,
        saved_at=datetime.now(UTC),
    )
    items.append(saved)
    _write(user, items)
    return saved


def remove_saved(user: UserContext, saved_id: str) -> bool:
    """Remove a saved recommendation by id. Returns True if removed."""
    items = _read(user)
    filtered = [r for r in items if r.id != saved_id]
    if len(filtered) == len(items):
        return False
    _write(user, filtered)
    return True
