"""Coordinator runtime.

Exposes `run_coordinator()` — the single function that runs the Coordinator
session end-to-end, captures the final structured EnablementPlan via the
`submit_enablement_plan` SDK MCP tool, and returns it.

Spec deviation note: BUILD_PLAN.md Phase 4.6 sketches subagent registration
as `coordinator.subagents = [...]` on an AgentDefinition object. The real
`claude-agent-sdk==0.1.81` API registers subagents via
`ClaudeAgentOptions.agents: dict[str, AgentDefinition]`. We implement
the SDK pattern. The Phase 4.6 plan text is otherwise unchanged.
"""

from __future__ import annotations

import logging
import uuid
from pathlib import Path
from typing import Any

from claude_agent_sdk import (
    AgentDefinition,
    AssistantMessage,
    ClaudeAgentOptions,
    HookMatcher,
    ResultMessage,
    SystemMessage,
    create_sdk_mcp_server,
    query,
    tool,
)
from claude_agent_sdk.types import HookEvent

from coordinator.definition import (
    COORDINATOR_TOOLS,
    COORDINATOR_VERSION,
    SUBMIT_PLAN_TOOL_NAME,
    coordinator_definition,
)
from coordinator.hooks.enforce_credentials import enforce_credentials
from coordinator.hooks.enforce_writes import enforce_writes
from coordinator.hooks.normalize_responses import normalize_responses
from coordinator.schemas import CoordinatorRunResult, EnablementPlan

logger = logging.getLogger(__name__)

# Repo root. Resolved relative to this file so the runtime always picks the
# correct cwd no matter where it's invoked from.
_REPO_ROOT: Path = Path(__file__).resolve().parent.parent

# Name of the SDK MCP server that hosts our submit tool. The submit tool's
# fully-qualified name (used in allowed_tools) is mcp__<server>__<tool>.
_COORDINATOR_MCP_SERVER_NAME = "coordinator"


def _register_subagents() -> dict[str, AgentDefinition]:
    """Subagent registry — the Coordinator's `Task` tool delegates to these.

    Each key is the subagent name that the Coordinator passes when invoking
    `Task`. Each value is the AgentDefinition the SDK uses to run that
    subagent in isolated context.

    Phase 4.6: Support Enablement Agent registered.
    """
    from enablement_agents.support.definition import (
        SUPPORT_AGENT_NAME,
        support_enablement_agent,
    )
    return {SUPPORT_AGENT_NAME: support_enablement_agent}


def _build_hooks() -> dict[HookEvent, list[HookMatcher]]:
    """Register the three Phase 3 hooks.

    `enforce_credentials` and `enforce_writes` both fire on PreToolUse —
    they are independent matchers so a deny from either is sufficient. The
    SDK runs all matchers and respects the first deny.
    """
    hooks: dict[HookEvent, list[HookMatcher]] = {
        "PreToolUse": [
            HookMatcher(hooks=[enforce_credentials]),
            HookMatcher(hooks=[enforce_writes]),
        ],
        "PostToolUse": [
            HookMatcher(hooks=[normalize_responses]),
        ],
    }
    return hooks


def _build_submit_tool_and_server(
    captured: dict[str, EnablementPlan],
) -> Any:
    """Construct the submit_enablement_plan tool and its in-process MCP server.

    The tool's `input_schema` is the EnablementPlan JSON Schema generated by
    Pydantic. When the Coordinator calls this tool, we re-validate the args
    through Pydantic and stash the resulting EnablementPlan in `captured`.

    Returning a server-config object (suitable for ClaudeAgentOptions.mcp_servers).
    """
    schema = EnablementPlan.model_json_schema()

    @tool(
        "submit_enablement_plan",
        (
            "Submit the final structured EnablementPlan for this Coordinator run. "
            "Call this exactly once when your work is complete. The input must "
            "conform to the EnablementPlan Pydantic schema. Extra keys are rejected; "
            "missing required fields are rejected; enum values must match exactly. "
            "After this tool is called successfully, your turn is done."
        ),
        schema,
    )
    async def submit_enablement_plan(args: dict[str, Any]) -> dict[str, Any]:
        try:
            plan = EnablementPlan.model_validate(args)
        except Exception as exc:  # noqa: BLE001 — surface validation error to the agent
            return {
                "content": [
                    {
                        "type": "text",
                        "text": (
                            "EnablementPlan validation failed. Fix the structured "
                            f"output and call submit_enablement_plan again. Error: {exc}"
                        ),
                    }
                ],
                "is_error": True,
            }
        captured["plan"] = plan
        logger.info(
            "submit_enablement_plan captured plan dept=%s findings=%d recs=%d",
            plan.department,
            len(plan.capability_coverage),
            len(plan.recommendations),
        )
        return {
            "content": [
                {
                    "type": "text",
                    "text": (
                        f"Plan accepted for department '{plan.department}'. "
                        f"{len(plan.capability_coverage)} capability findings, "
                        f"{len(plan.recommendations)} recommendations."
                    ),
                }
            ]
        }

    server = create_sdk_mcp_server(
        name=_COORDINATOR_MCP_SERVER_NAME,
        version=COORDINATOR_VERSION,
        tools=[submit_enablement_plan],
    )
    return server


async def run_coordinator(request: str) -> CoordinatorRunResult:
    """Run a single Coordinator session and return the captured EnablementPlan.

    Args:
        request: Free-text inbound enablement request (e.g., "Enable AI for
            customer support").

    Returns:
        CoordinatorRunResult wrapping the validated EnablementPlan.

    Raises:
        RuntimeError: If the Coordinator finishes without calling
            `submit_enablement_plan`.
    """
    if not request.strip():
        raise ValueError("Coordinator request must be a non-empty string.")

    captured: dict[str, EnablementPlan] = {}
    submit_server = _build_submit_tool_and_server(captured)

    # Register every MCP server any subagent might reach into. The subagent's
    # AgentDefinition.mcpServers field lists which of these it can access
    # (by name); but the actual server instances must live on the parent
    # ClaudeAgentOptions.mcp_servers dict.
    mcp_servers = {_COORDINATOR_MCP_SERVER_NAME: submit_server}
    # Phase 4.6: support agent needs lookup_tool_capability.
    from enablement_agents.support.tools import (  # local import to avoid cycle
        SUPPORT_MCP_SERVER_NAME,
        build_support_mcp_server,
    )
    mcp_servers[SUPPORT_MCP_SERVER_NAME] = build_support_mcp_server()

    options = ClaudeAgentOptions(
        system_prompt=coordinator_definition.prompt,
        allowed_tools=[*COORDINATOR_TOOLS, SUBMIT_PLAN_TOOL_NAME],
        mcp_servers=mcp_servers,
        hooks=_build_hooks(),
        agents=_register_subagents(),
        cwd=str(_REPO_ROOT),
    )

    coordinator_session_id: str | None = None

    async for message in query(prompt=request, options=options):
        # SystemMessage at session start carries the session id.
        if isinstance(message, SystemMessage):
            sid = getattr(message, "session_id", None) or getattr(message, "data", {}).get(
                "session_id"
            )
            if isinstance(sid, str) and not coordinator_session_id:
                coordinator_session_id = sid

        # AssistantMessages and ResultMessages flow through — the submit tool
        # captures the plan when the model decides to call it. We don't act
        # on them here; we just need the loop to drain.
        if isinstance(message, (AssistantMessage, ResultMessage)):
            pass

    if "plan" not in captured:
        raise RuntimeError(
            "Coordinator finished without calling submit_enablement_plan. "
            "Check the system prompt and the agent's final turn for what went wrong."
        )

    return CoordinatorRunResult(
        plan=captured["plan"],
        coordinator_session_id=coordinator_session_id or f"sess-unknown-{uuid.uuid4()}",
    )
