"""Tests for the generated support orchestrator runtime.

Phase 7.3 — these tests run against the actual generated tree under
``orchestrators/support/`` (regenerated by ``tests/conftest.py`` if
missing). They never hit a live LLM — the orchestrator runs in demo mode
(stub classifier, stub draft, stub LD events) by virtue of
``ENABLE_AI_DEMO_MODE=true`` being the default.

What's covered:

  - The generated package imports cleanly.
  - The observability module declares the expected span names.
  - ``orchestrator.py`` references each expected span name (so a future
    refactor that drops a span instrumentation point is caught here).
  - The four documented intent classes produce the documented
    ``action_taken`` against fixture inquiries.
  - Successful and error-path responses conform to ``SupportResponse``.
"""

from __future__ import annotations

import importlib

import pytest


@pytest.fixture(autouse=True)
def _demo_mode_on(monkeypatch: pytest.MonkeyPatch) -> None:
    """Force demo mode for runtime tests — no real LLM / LD calls."""
    monkeypatch.setenv("ENABLE_AI_DEMO_MODE", "true")
    monkeypatch.delenv("ANTHROPIC_API_KEY", raising=False)
    monkeypatch.delenv("LAUNCHDARKLY_SDK_KEY", raising=False)


# ---------------------------------------------------------------------------
# Import smoke tests
# ---------------------------------------------------------------------------


def test_orchestrator_module_imports() -> None:
    mod = importlib.import_module("orchestrators.support.orchestrator")
    assert hasattr(mod, "handle_inquiry")
    assert hasattr(mod, "Inquiry")
    assert hasattr(mod, "SupportResponse")


def test_observability_module_imports() -> None:
    mod = importlib.import_module("orchestrators.support.observability")
    assert hasattr(mod, "span")
    assert hasattr(mod, "EXPECTED_SPAN_NAMES")
    assert isinstance(mod.EXPECTED_SPAN_NAMES, tuple)


def test_hubspot_mcp_server_imports() -> None:
    mod = importlib.import_module(
        "orchestrators.support.mcp_servers.hubspot.server"
    )
    assert callable(mod.build_hubspot_mcp_server)


# ---------------------------------------------------------------------------
# OTel span contract — Phase 5.2 names must all appear in orchestrator.py
# ---------------------------------------------------------------------------


_REQUIRED_SPAN_NAMES: tuple[str, ...] = (
    "support_orchestrator.handle_inquiry",
    "support_orchestrator.fetch_ai_config",
    "support_orchestrator.classify_intent",
    "support_orchestrator.knowledge_base.search",
    "support_orchestrator.draft_response",
    "support_orchestrator.build_handoff",
    "support_orchestrator.emit_events",
)


def test_expected_span_names_declared() -> None:
    obs = importlib.import_module("orchestrators.support.observability")
    for name in _REQUIRED_SPAN_NAMES:
        assert name in obs.EXPECTED_SPAN_NAMES, f"missing span: {name}"


def test_orchestrator_py_references_each_expected_span() -> None:
    from pathlib import Path

    orch_py = (
        Path(__file__).resolve().parents[2]
        / "orchestrators"
        / "support"
        / "orchestrator.py"
    ).read_text(encoding="utf-8")
    for name in _REQUIRED_SPAN_NAMES:
        assert name in orch_py, f"orchestrator.py doesn't emit span: {name}"


# ---------------------------------------------------------------------------
# Behavioral contract — Phase 5.2 intent classes
# ---------------------------------------------------------------------------


async def test_handle_inquiry_classifies_refund() -> None:
    mod = importlib.import_module("orchestrators.support.orchestrator")
    inq = mod.Inquiry(
        subject="Cancellation request",
        body="I need to cancel and would like a refund.",
        customer_id="CUST-009",
    )
    response = await mod.handle_inquiry(inq, request_id="test-refund-1")
    assert response.intent == "REFUND"
    assert response.action_taken == "auto_drafted_for_review"
    assert response.escalated is False
    assert response.citations  # refund replies cite policy
    assert response.error is None


async def test_handle_inquiry_classifies_escalation() -> None:
    mod = importlib.import_module("orchestrators.support.orchestrator")
    inq = mod.Inquiry(
        subject="Need a manager",
        body="Please escalate to your supervisor immediately.",
        customer_id="CUST-001",
    )
    response = await mod.handle_inquiry(inq, request_id="test-escalation-1")
    assert response.intent == "ESCALATION"
    assert response.action_taken == "escalated_to_team_lead"
    assert response.escalated is True
    assert response.error is None


async def test_handle_inquiry_classifies_status() -> None:
    mod = importlib.import_module("orchestrators.support.orchestrator")
    inq = mod.Inquiry(
        subject="Status update",
        body="When will my booking be confirmed?",
        customer_id="CUST-005",
    )
    response = await mod.handle_inquiry(inq, request_id="test-status-1")
    assert response.intent == "STATUS"
    assert response.action_taken == "auto_acknowledged"
    assert response.escalated is False
    assert response.error is None


async def test_handle_inquiry_classifies_faq() -> None:
    mod = importlib.import_module("orchestrators.support.orchestrator")
    inq = mod.Inquiry(
        subject="Policy question",
        body="What is your policy on welcome bags?",
        customer_id="CUST-001",
    )
    response = await mod.handle_inquiry(inq, request_id="test-faq-1")
    assert response.intent == "FAQ"
    assert response.action_taken == "auto_resolved_with_kb"
    assert response.error is None


async def test_handle_inquiry_response_shape() -> None:
    """Whatever intent, the response always has these fields with valid types."""
    mod = importlib.import_module("orchestrators.support.orchestrator")
    inq = mod.Inquiry(
        subject="Generic",
        body="Just touching base.",
        customer_id="CUST-014",
    )
    response = await mod.handle_inquiry(inq)
    # The Pydantic model validates these for us; here we just probe the shape.
    assert response.intent in {"FAQ", "REFUND", "ESCALATION", "STATUS", "OTHER"}
    assert isinstance(response.draft_reply, str)
    assert 0.0 <= response.confidence <= 1.0
    assert isinstance(response.action_taken, str)
    assert isinstance(response.citations, list)
    assert isinstance(response.escalated, bool)
    # error is None in the success path
    assert response.error is None
